'use strict';
// Compact payload columns are shared with build_data.R. All data text reaches the
// DOM through textContent, never HTML. Imported files never leave this browser.
const F={id:0,name:1,l2:2,l3:3,lon:4,lat:5,aliases:6,eligible:7,review:8,aff:9,source:10,sourceId:11,hold:12,family:13,ordinal:14};
function parseCSV(text){
  text=text.replace(/^\uFEFF/,''); const rows=[];let row=[],cell='',quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||cell===''){quoted=!quoted;}else throw Error('Quote inside an unquoted field.');}
    else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';}else cell+=c;}
  if(quoted)throw Error('Unclosed quoted CSV field.');row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows;
}
function importedRows(text){
  const csv=parseCSV(text);if(csv.length<2)throw Error('The CSV needs a header and at least one record.');
  const header=csv.shift().map(v=>v.trim());if(new Set(header).size!==header.length)throw Error('Duplicate column name.');
  const required=['entity_id','primary_name','name_expanded','name_core','lon','lat'];for(const n of required)if(!header.includes(n))throw Error('Missing column: '+n);
  if(csv.length>50000)throw Error('The local preview limit is 50,000 rows.');const ids=new Set();
  return csv.map((r,i)=>{if(r.length!==header.length)throw Error('Column count differs on row '+(i+2));const o=Object.fromEntries(header.map((h,j)=>[h,r[j]]));
    if(!o.entity_id||ids.has(o.entity_id))throw Error('Missing or duplicate entity_id on row '+(i+2));ids.add(o.entity_id);
    if(!o.primary_name||!o.name_expanded||!o.name_core)throw Error('Empty name on row '+(i+2));
    const lon=Number(o.lon),lat=Number(o.lat);if(o.lon.trim()===''||o.lat.trim()===''||!Number.isFinite(lon)||!Number.isFinite(lat)||Math.abs(lon)>180||Math.abs(lat)>90)throw Error('Invalid coordinates on row '+(i+2));
    const parseBool=(v,fallback)=>{if(v===undefined||v==='')return fallback;if(/^(true|1)$/i.test(v))return true;if(/^(false|0)$/i.test(v))return false;throw Error('Invalid boolean on row '+(i+2));};
    const eligible=parseBool(o.analysis_eligible,true);const affiliated=parseBool(o.is_franchise,null);
    // Imported review claims are retained as context, never elevated to verified.
    return [o.entity_id,o.primary_name,o.name_expanded,o.name_core,lon,lat,o.alt_names||'',eligible,'unverified import',affiliated===null?'unknown':affiliated?'affiliated':'independent',o.source||'user supplied',o.source_id||o.entity_id,o.analysis_exclusion||'',o.denom_norm||'',o.ordinal?Number(o.ordinal):null];});
}
function inScope(row,scope,category){return scope==='all'||(scope==='affiliated'?row[F.eligible]&&row[F.aff]==='affiliated':row[F.eligible]&&(category!=='museums'||row[F.aff]!=='affiliated'));}
function makeIndex(rows,level){const groups=new Map();for(const r of rows){const name=r[F[level]];if(!name)continue;let g=groups.get(name);if(!g){g=[name,'local',0,0,0,0];groups.set(name,g);}g[5]++;if(r[F.eligible]){g[3]++;if(r[F.aff]==='affiliated')g[4]++;else g[2]++;}}return [...groups.values()];}
function groupCount(g,scope,category){return scope==='all'?g[5]:scope==='affiliated'?g[4]:category==='museums'?g[2]:g[3];}
function csvCell(value){let s=value==null?'':String(value);if(/^[=+@\-\t\r]/.test(s)&&typeof value!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
if(typeof module!=='undefined')module.exports={parseCSV,importedRows,inScope,makeIndex,groupCount,csvCell,F};
if(typeof document!=='undefined'){
  const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString();
  let manifest,index=[],category='museums',level='l2',scope='eligible',selected='',rows=[],groupLimit=50,rowLimit=50,loadToken=0,mapReady=false,customRows=null,map;
  const bucketCache=new Map();let popup,exportURL,indexLoading=false;
  const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
  function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';}
  async function json(path){const url=manifest?path+'?snapshot='+encodeURIComponent(manifest.built_utc):path;const response=await fetch(url,{cache:manifest?'default':'no-store'});if(!response.ok)throw Error('Missing build file: '+path);if(path.endsWith('.gz')){if(typeof DecompressionStream==='undefined')throw Error('This browser cannot read compressed data; use a current browser.');return await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).json();}return await response.json();}
  function count(g){return groupCount(g,scope,category);}
  function updateNote(){const notes={museums:'Museum default: L2, eligible candidates excluding known chains. Unknown affiliation does not mean independent.',churches:'Church default: L3, provisional Christian worship sites. Independent labels and congregation-versus-campus reviews are pending.',custom:'Local CSV · user-supplied, unverified records. No file or record is uploaded.'};$('scope-note').textContent=notes[category];}
  function renderGroups(){const q=$('search').value.trim().toLocaleLowerCase();const groups=index.filter(g=>count(g)>0&&g[0].toLocaleLowerCase().includes(q)).sort((a,b)=>count(b)-count(a)||a[0].localeCompare(b[0]));
    $('group-count').textContent=fmt(groups.length)+' matches';$('groups').replaceChildren();for(const g of groups.slice(0,groupLimit)){const b=node('button',null,'group');b.setAttribute('aria-pressed',String(g[0]===selected));b.append(node('span',g[0]),node('strong',fmt(count(g))));b.addEventListener('click',()=>selectGroup(g));$('groups').append(b);}
    if(!groups.length)$('groups').append(node('p','No names match these filters.','muted'));$('more-groups').hidden=groups.length<=groupLimit;return groups;
  }
  async function loadCategory(){const token=++loadToken;indexLoading=true;selected='';rows=[];index=[];groupLimit=50;rowLimit=50;clearDetail();updateNote();status('Loading '+(category==='custom'?'local records':category)+'…');
    try{const next=category==='custom'?makeIndex(customRows,level):await json('data/'+category+'-'+level+'-index.json.gz');if(token!==loadToken)return;index=next;indexLoading=false;const groups=renderGroups();status('Local snapshot loaded. Select a name to inspect its records.');if(groups.length)await selectGroup(groups[0]);}catch(e){if(token!==loadToken)return;indexLoading=false;status(e.message,true);}}
  function clearExport(){if(exportURL){URL.revokeObjectURL(exportURL);exportURL=null;}$('export-ready').hidden=true;}
  function clearDetail(){clearExport();$('selected-name').textContent='Choose a name';$('selected-summary').textContent='';$('records').replaceChildren();$('table-caption').textContent='No records selected.';$('download').disabled=true;$('more-records').hidden=true;drawMap();}
  async function selectGroup(g){clearExport();const token=++loadToken;selected=g[0];rowLimit=50;renderGroups();$('selected-name').textContent=selected;status('Loading institution records…');
    try{let all;if(category==='custom')all=customRows;else{const path='data/'+category+'-'+level+'-'+g[1]+'.json.gz';all=bucketCache.get(path);if(!all){all=await json(path);if(bucketCache.size>5)bucketCache.delete(bucketCache.keys().next().value);bucketCache.set(path,all);}}
      if(token!==loadToken)return;rows=all.filter(r=>r[F[level]]===selected&&inScope(r,scope,category));rows.sort((a,b)=>a[F.name].localeCompare(b[F.name])||a[F.id].localeCompare(b[F.id]));
      if(rows.length!==count(g))throw Error('Index and records disagree. Rebuild the data snapshot.');const verified=rows.filter(r=>r[F.review]==='verified').length,unknown=rows.filter(r=>r[F.aff]==='unknown').length,held=rows.filter(r=>!r[F.eligible]).length;
      $('selected-summary').textContent=fmt(rows.length)+' records · '+fmt(verified)+(verified===1?' factual review':' factual reviews')+' marked verified · '+fmt(unknown)+' unknown affiliations'+(held?' · '+fmt(held)+' holds':'');$('download').disabled=!rows.length;renderRows();drawMap(true);status('Showing '+fmt(rows.length)+' records for “'+selected+'”.');
    }catch(e){rows=[];renderRows();drawMap();$('download').disabled=true;status(e.message,true);}}
  function recordPopup(r){const box=node('div',null,'popup');box.append(node('strong',r[F.name]));if(r[F.aliases])box.append(node('p','Source aliases: '+r[F.aliases]));box.append(node('p','Review: '+r[F.review]+' · Affiliation: '+r[F.aff]),node('p',r[F.eligible]?'Eligible for this analysis':'Hold: '+(r[F.hold]||'not eligible')),node('p',r[F.source]+' · '+r[F.sourceId]),node('p',r[F.lat].toFixed(5)+', '+r[F.lon].toFixed(5)),node('p','Source coordinates; visitor access is not certified.'));return box;}
  function showRecord(r){if(!mapReady){status('Map unavailable; the complete record remains in the table.');return;}if(popup)popup.remove();map.flyTo({center:[r[F.lon],r[F.lat]],zoom:11,duration:0});popup=new maplibregl.Popup({maxWidth:'310px'}).setLngLat([r[F.lon],r[F.lat]]).setDOMContent(recordPopup(r)).addTo(map);}
  function renderRows(){$('records').replaceChildren();for(const r of rows.slice(0,rowLimit)){const tr=node('tr'),name=node('td'),review=node('td'),source=node('td');const b=node('button',r[F.name],'name-button');b.addEventListener('click',()=>showRecord(r));name.append(b);if(r[F.aliases])name.append(node('span','Source aliases: '+r[F.aliases],'alias'));name.append(node('span',r[F.id],'alias'));
      review.append(node('span',r[F.review],'badge'),node('span',r[F.aff],'badge'));if(!r[F.eligible])review.append(node('span','Hold: '+(r[F.hold]||'not eligible'),'alias'));if(r[F.family])review.append(node('span','Family: '+r[F.family],'alias'));
      source.append(node('span',r[F.source]),node('span',r[F.sourceId],'alias'),node('span',r[F.lat].toFixed(5)+', '+r[F.lon].toFixed(5),'alias'));tr.append(name,review,source);$('records').append(tr);}
    $('table-caption').textContent='Showing '+fmt(Math.min(rowLimit,rows.length))+' of '+fmt(rows.length)+' records. Source aliases are preserved.';$('more-records').hidden=rows.length<=rowLimit;}
  function fitRows(){if(!mapReady||!rows.length)return;const xs=rows.map(r=>r[F.lon]),ys=rows.map(r=>r[F.lat]);let west=Math.min(...xs),east=Math.max(...xs);if(east-west>180){const shifted=xs.map(x=>x<0?x+360:x);west=Math.min(...shifted);east=Math.max(...shifted);}map.fitBounds([[west,Math.min(...ys)],[east,Math.max(...ys)]],{padding:65,maxZoom:10,duration:0});}
  function drawMap(fit=false){if(!mapReady)return;if(popup)popup.remove();map.getSource('records').setData({type:'FeatureCollection',features:rows.map((r,i)=>({type:'Feature',geometry:{type:'Point',coordinates:[r[F.lon],r[F.lat]]},properties:{row:i,color:!r[F.eligible]?'#eb6834':r[F.aff]==='affiliated'?'#1baf7a':'#2a78d6'}}))});if(fit)fitRows();}
  async function initMap(){try{const states=await json('data/states.geojson.gz');map=new maplibregl.Map({container:'map',center:[-96,38],zoom:3,style:{version:8,sources:{states:{type:'geojson',data:states},records:{type:'geojson',data:{type:'FeatureCollection',features:[]}}},layers:[{id:'background',type:'background',paint:{'background-color':'#f9f9f7'}},{id:'states',type:'fill',source:'states',paint:{'fill-color':'#fcfcfb','fill-outline-color':'#c3c2b7'}},{id:'records',type:'circle',source:'records',paint:{'circle-radius':5,'circle-color':['get','color'],'circle-opacity':.8,'circle-stroke-width':.5,'circle-stroke-color':'white'}}]},attributionControl:false});
      map.addControl(new maplibregl.NavigationControl(),'top-right');map.addControl(new maplibregl.AttributionControl({customAttribution:'Census 2023 · source coordinates · no remote tiles',compact:true}));map.on('load',()=>{mapReady=true;drawMap(true);});map.on('click','records',e=>{const r=rows[e.features[0].properties.row];if(r)showRecord(r);});map.on('mouseenter','records',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','records',()=>map.getCanvas().style.cursor='');
      map.on('error',e=>{status('Map error: '+e.error.message+'. The record table remains available.',true);});
    }catch(e){$('map').append(node('p','Map unavailable: '+e.message+'. Use the record table below.','notice'));}}
  $('category').addEventListener('change',()=>{category=$('category').value;level=category==='museums'?'l2':'l3';$('level').value=level;scope='eligible';$('scope').value=scope;$('search').value='';loadCategory();});
  $('level').addEventListener('change',()=>{level=$('level').value;loadCategory();});$('scope').addEventListener('change',()=>{scope=$('scope').value;if(indexLoading)return;const groups=renderGroups();if(groups.length)selectGroup(groups.find(g=>g[0]===selected)||groups[0]);else{++loadToken;rows=[];selected='';clearDetail();status('No records in this scope.');}});
  $('search').addEventListener('input',()=>{groupLimit=50;renderGroups();});$('more-groups').addEventListener('click',()=>{groupLimit+=50;renderGroups();});$('more-records').addEventListener('click',()=>{rowLimit+=50;renderRows();});$('fit').addEventListener('click',fitRows);
  for(const b of document.querySelectorAll('[data-region]'))b.addEventListener('click',()=>{const bounds={lower48:[[-125,24],[-66,50]],alaska:[[-170,51],[-130,72]],hawaii:[[-161,18],[-154,23]]};if(mapReady)map.fitBounds(bounds[b.dataset.region],{padding:45,duration:0});});
  $('download').addEventListener('click',()=>{const header=['entity_id','primary_name','name_expanded','name_core','lon','lat','alt_names','analysis_eligible','review_status','affiliation','source','source_id','analysis_exclusion','denom_norm','ordinal'];const csv=[header.map(csvCell).join(','),...rows.map(r=>r.map(csvCell).join(','))].join('\r\n');clearExport();exportURL=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=$('export-link');a.href=exportURL;a.download='duplicate-names-'+category+'-'+level+'.csv';$('export-details').textContent=fmt(rows.length)+' selected records; aliases and review status included.';$('export-ready').hidden=false;a.click();});
  $('import').addEventListener('change',async()=>{const file=$('import').files[0];if(!file)return;try{if(file.size>30*1024*1024)throw Error('The local file limit is 30 MB.');const next=importedRows(await file.text());customRows=next;if(![...$('category').options].some(o=>o.value==='custom')){const option=node('option','Local CSV · unverified');option.value='custom';$('category').append(option);}category='custom';level='l3';scope='eligible';$('category').value=category;$('level').value=level;$('scope').value=scope;$('search').value='';$('import-status').textContent=fmt(next.length)+' records loaded locally. No upload occurred.';await loadCategory();}catch(e){$('import-status').textContent=e.message;}});
  (async()=>{try{manifest=await json('data/manifest.json');$('provenance').textContent='Snapshot '+manifest.built_utc+'. Overture '+manifest.overture_release+'; IMLS 2018 museum archive; explicit museum decisions and Census TIGER/Line 2023. Analysis and source rows are preserved in the repository. Cloud resource spending: $0.';await Promise.all([initMap(),loadCategory()]);}catch(e){status(e.message+' Run dashboard/build_data.R before opening this page.',true);}})();
}

